export const loginFormFields = [
  {
    label: 'Email Address',
    name: 'email',
    type: 'email',
    required: true,
    keyboardType: 'email-address' as const,
    autoCapitalize: 'none' as const,
    autoComplete: 'email' as const,
    textContentType: 'emailAddress' as const,
    placeholder: 'Enter your email address',
  },
  {
    label: 'Password',
    name: 'password',
    type: 'password',
    required: true,
    isPassword: true,
    autoComplete: 'password' as const,
    textContentType: 'password' as const,
    placeholder: 'Enter your password',
  },
];

export const registerFormFields = [
  {
    label: 'Email Address',
    name: 'email',
    type: 'email',
    required: true,
    keyboardType: 'email-address' as const,
    autoCapitalize: 'none' as const,
    autoComplete: 'email' as const,
    textContentType: 'emailAddress' as const,
    placeholder: 'Enter your email address',
  },

  {
    label: 'Password',
    name: 'password',
    type: 'password',
    required: true,
    isPassword: true,
    autoComplete: 'password' as const,
    textContentType: 'password' as const,
    hint: 'Must contain uppercase, lowercase, and number',
    placeholder: 'Enter your password',
  },
  {
    label: 'First Name',
    name: 'firstName',
    type: 'text',
    required: true,
    autoCapitalize: 'words' as const,
    textContentType: 'givenName' as const,
    placeholder: 'Enter your first name',
  },
  {
    label: 'Last Name',
    name: 'lastName',
    type: 'text',
    required: true,
    autoCapitalize: 'words' as const,
    textContentType: 'familyName' as const,
    placeholder: 'Enter your last name',
  },
  {
    label: 'Phone Number',
    name: 'phone',
    type: 'phone',
    required: true,
    keyboardType: 'phone-pad' as const,
    textContentType: 'telephoneNumber' as const,
    placeholder: '+1 (555) 123-4567',
  },
];
